<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;
use App\Models\Product;
class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('product') ->insert([
            [
                'name' => 'Glorned Gloves',
                'category_id' => 1,
<<<<<<< HEAD
                'brand_id' => 1,
                'suppliers_id' => 1,
                'stock' => 20,
                'stock_warning' => 20,
=======
                'brand_id' => 5,
                'stock' => 40,
>>>>>>> ef57359fd894ee32ceb516246ccc1af1ff09f8aa
                'SKU' => 'GLO212',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Microsuper Gloves',
                'category_id' => 1,
<<<<<<< HEAD
                'brand_id' => 1,
                'suppliers_id' => 1,
                'stock' => 20,
                'stock_warning' => 20,
                'SKU' => 'MIC101',
=======
                'brand_id' => 5,
                'stock' => 40,
                'SKU' => 'GLO213',
>>>>>>> ef57359fd894ee32ceb516246ccc1af1ff09f8aa
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
<<<<<<< HEAD
                'name' => 'HCD',
                'category_id' => 1,
                'brand_id' => 1,
                'suppliers_id' => 1,
                'stock' => 19,
                'stock_warning' => 20,
                'SKU' => 'HCD101',
=======
                'name' => 'HCD Gloves',
                'category_id' => 1,
                'brand_id' => 5,
                'stock' => 40,
                'SKU' => 'GLO215',
>>>>>>> ef57359fd894ee32ceb516246ccc1af1ff09f8aa
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
<<<<<<< HEAD
            ]
            ,[
                'name' => 'Stainless Steel Upper & Lower Ovoid',
                'category_id' => 20,
                'brand_id' => 1,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 18,
                'SKU' => 'SSO001',
                'cprice' => 40,
                'sprice' => 80.00,
=======
            ],
            [
                'name' => 'Defender Mask',
                'category_id' => 2,
                'brand_id' => 8,
                'stock' => 40,
                'SKU' => 'Mas213',
                'cprice' => 100,
                'sprice' => 350.00,
>>>>>>> ef57359fd894ee32ceb516246ccc1af1ff09f8aa
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
<<<<<<< HEAD
                'name' => 'Stainless Steel Upper & Lower Square',
                'category_id' => 20,
                'brand_id' => 1,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'SSS002',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Reverse Curve Wire Ovoid',
                'category_id' => 20,
                'brand_id' => 1,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'RCW001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Open Coil Spring',
                'category_id' => 20,
                'brand_id' => 1,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'OCS001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Co Axial Wire',
                'category_id' => 20,
                'brand_id' => 1,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'CAW001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Standard Buccaltubes',
                'category_id' => 21,
                'brand_id' => 1,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'STB001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Convertible Buccaltubes',
                'category_id' => 21,
                'brand_id' => 1,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'COB001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Second Molar Buccaltubes',
                'category_id' => 21,
                'brand_id' => 1,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'SMB001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Standard Roth',
                'category_id' => 25,
                'brand_id' => 1,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'STR001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Standard MBT',
                'category_id' => 25,
                'brand_id' => 1,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'SMT001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Mini Roth',
                'category_id' => 25,
                'brand_id' => 1,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'MMT001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Edgewise',
                'category_id' => 25,
                'brand_id' => 1,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'EDG001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Self Ligating Brackets in high end and in midrange class in Roth & MBT',
                'category_id' => 25,
                'brand_id' => 1,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'SLB001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Movable Hooks',
                'category_id' => 22,
                'brand_id' => 1,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'MOH001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Crimbpable Hooks',
                'category_id' => 22,
                'brand_id' => 1,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'CRH001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Lingual Button',
                'category_id' => 2,
                'brand_id' => 1,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'LBT001',
                'cprice' => 40,
                'sprice' => 80.00,
=======
                'name' => 'Ordinary Mask',
                'category_id' => 2,
                'brand_id' => 1,
                'stock' => 40,
                'SKU' => 'Mas234',
                'cprice' => 40,
                'sprice' => 65.00,
>>>>>>> ef57359fd894ee32ceb516246ccc1af1ff09f8aa
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
<<<<<<< HEAD
                'name' => 'Lingual Retainer',
                'category_id' => 22,
                'brand_id' => 1,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'LIR001',
                'cprice' => 40,
                'sprice' => 80.00,
=======
                'name' => 'KN 95',
                'category_id' => 2,
                'brand_id' => 1,
                'stock' => 40,
                'SKU' => 'Mas245',
                'cprice' => 40,
                'sprice' => 35.00,
>>>>>>> ef57359fd894ee32ceb516246ccc1af1ff09f8aa
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
<<<<<<< HEAD
            ],[
                'name' => 'Ligaties',
                'category_id' => 23,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'LIG001',
                'cprice' => 40,
                'sprice' => 80.00,
=======
            ],
            [
                'name' => '2ply disposable',
                'category_id' => 3,
                'brand_id' => 6,
                'stock' => 40,
                'SKU' => 'Bb222',
                'cprice' => 40,
                'sprice' => 35.00,
>>>>>>> ef57359fd894ee32ceb516246ccc1af1ff09f8aa
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
<<<<<<< HEAD
            ],[
                'name' => 'Echain',
                'category_id' => 23,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'ECH001',
                'cprice' => 40,
                'sprice' => 80.00,
=======
            ],
            [
                'name' => '3ply disposable',
                'category_id' => 3,
                'brand_id' => 1,
                'stock' => 40,
                'SKU' => 'Bb223',
                'cprice' => 40,
                'sprice' => 35.00,
>>>>>>> ef57359fd894ee32ceb516246ccc1af1ff09f8aa
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
<<<<<<< HEAD
            ],[
                'name' => 'Elastics 3.5oz',
                'category_id' => 23,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'ELA001',
                'cprice' => 40,
                'sprice' => 80.00,
=======
            ],
            [
                'name' => 'Washable bib Adult',
                'category_id' => 3,
                'brand_id' => 5,
                'stock' => 40,
                'SKU' => 'Bb224',
                'cprice' => 40,
                'sprice' => 35.00,
>>>>>>> ef57359fd894ee32ceb516246ccc1af1ff09f8aa
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
<<<<<<< HEAD
            ],[
                'name' => 'Elastics 4.5oz',
                'category_id' => 23,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'ELA002',
                'cprice' => 40,
                'sprice' => 80.00,
=======
            ],
            [
                'name' => 'Washable bib pedo',
                'category_id' => 3,
                'brand_id' => 5,
                'stock' => 40,
                'SKU' => 'Bb225',
                'cprice' => 40,
                'sprice' => 180.00,
>>>>>>> ef57359fd894ee32ceb516246ccc1af1ff09f8aa
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
<<<<<<< HEAD
            ],[
                'name' => 'Elastics 5oz',
                'category_id' => 23,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'ELA003',
                'cprice' => 40,
                'sprice' => 80.00,
=======
            ],
            [
                'name' => 'Saliva Injector Wordwork',
                'category_id' => 4,
                'brand_id' => 5,
                'stock' => 40,
                'SKU' => 'SUC111',
                'cprice' => 40,
                'sprice' => 150.00,
>>>>>>> ef57359fd894ee32ceb516246ccc1af1ff09f8aa
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
<<<<<<< HEAD
            ],[
                'name' => 'Molar Separator',
                'category_id' => 23,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'MSE001',
                'cprice' => 40,
                'sprice' => 80.00,
=======
            ],
            [
                'name' => 'Saliva Injector Micro',
                'category_id' => 4,
                'brand_id' => 5,
                'stock' => 40,
                'SKU' => 'SUC112',
                'cprice' => 40,
                'sprice' => 150.00,
>>>>>>> ef57359fd894ee32ceb516246ccc1af1ff09f8aa
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
<<<<<<< HEAD
            ],[
                'name' => 'Rotation Wedge',
                'category_id' => 23,
                'brand_id' => 2,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'ROW001',
                'cprice' => 40,
                'sprice' => 80.00,
=======
            ],
            [
                'name' => 'Saliva Injector Flexi',
                'category_id' => 4,
                'brand_id' => 5,
                'stock' => 40,
                'SKU' => 'SUC113',
                'cprice' => 40,
                'sprice' => 150.00,
>>>>>>> ef57359fd894ee32ceb516246ccc1af1ff09f8aa
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
<<<<<<< HEAD
            ],[
                'name' => 'Ortho Wax',
                'category_id' => 10,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'WAX001',
                'cprice' => 40,
                'sprice' => 80.00,
=======
            ],
            [
                'name' => 'High Vacuum',
                'category_id' => 4,
                'brand_id' => 5,
                'stock' => 40,
                'SKU' => 'SUC114',
                'cprice' => 40,
                'sprice' => 200.00,
>>>>>>> ef57359fd894ee32ceb516246ccc1af1ff09f8aa
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
<<<<<<< HEAD
            ],[
                'name' => 'Orthobrush',
                'category_id' => 10,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'OBR001',
                'cprice' => 40,
                'sprice' => 80.00,
=======
            ],
            [
                'name' => 'Surgical Sunction Tip',
                'category_id' => 4,
                'brand_id' => 5,
                'stock' => 40,
                'SKU' => 'SUC115',
                'cprice' => 40,
                'sprice' => 200.00,
>>>>>>> ef57359fd894ee32ceb516246ccc1af1ff09f8aa
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
<<<<<<< HEAD
            ],[
                'name' => 'Diestone',
                'category_id' => 10,
                'brand_id' => 3,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'DIE001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Castone',
                'category_id' => 10,
                'brand_id' => 3,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'CAS001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Plaster of Paris',
                'category_id' => 10,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'POP001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Alginate',
                'category_id' => 10,
                'brand_id' => 4,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'ALG001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Impression Tray',
                'category_id' => 10,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'ITR001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Rubber Impression',
                'category_id' => 10,
                'brand_id' => 4,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'RUI001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Rubber Dam',
                'category_id' => 10,
                'brand_id' => 4,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'RUB001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Cheek Retractor',
                'category_id' => 10,
                'brand_id' => 4,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'CHR001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Salivatip Ejector',
                'category_id' => 10,
                'brand_id' => 10,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'SAE001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Dentalbib',
                'category_id' => 10,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'DEB001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Cottonroll',
                'category_id' => 10,
                'brand_id' => 11,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'COT001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Gauze',
                'category_id' => 10,
                'brand_id' => 11,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'GAZ001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Suturing Needle',
                'category_id' => 10,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'SUN001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Suturing Thread',
                'category_id' => 10,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'SUT001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Lidocaine Ephiniprine',
                'category_id' => 26,
                'brand_id' => 12,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'LIE001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Mepivacaine',
                'category_id' => 26,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'MEP001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Atricaine',
                'category_id' => 26,
                'brand_id' => 15,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'ATR001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Dental Needle',
                'category_id' => 26,
                'brand_id' => 16,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'DEN001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Etchant',
                'category_id' => 27,
                'brand_id' => 19,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'ETC001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Composite Packable',
                'category_id' => 27,
                'brand_id' => 22,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'COP001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Composite Flow',
                'category_id' => 27,
                'brand_id' => 20,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'COF001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Dental Chair',
                'category_id' => 24,
                'brand_id' => 24,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'DEC001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Dental Highspeed',
                'category_id' => 24,
                'brand_id' => 25,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'DEH001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Dental Lowspeed',
                'category_id' => 24,
                'brand_id' => 25,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'DEL001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Micro Motor',
                'category_id' => 24,
                'brand_id' => 25,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'DCH001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Prophy Cup',
                'category_id' => 28,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'PRC001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Prophy Brush Ordinary',
                'category_id' => 28,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'PBC001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Prophypaste',
                'category_id' => 28,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'PPT001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'ProphyPaste Jar',
                'category_id' => 28,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'PPJ001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Flouride Varnish',
                'category_id' => 28,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'FLV001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Pumice',
                'category_id' => 28,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'PUM001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Pumice Mint',
                'category_id' => 28,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'PUM002',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Taxi',
                'category_id' => 28,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'TAX001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'C-Bond',
                'category_id' => 9,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'BON001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Uni-bond',
                'category_id' => 9,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'BON002',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'U-Bond Vericom',
                'category_id' => 9,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'BON003',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'BC Plus Bond Vericom',
                'category_id' => 9,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'BON004',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Applicator Tips',
                'category_id' => 10,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'APT001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Headcap',
                'category_id' => 10,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'HEC001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Paper Cup',
                'category_id' => 10,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'PAC001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Flouride Gel',
                'category_id' => 10,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'FLG001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Celluloid Strips',
                'category_id' => 10,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'CES001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Articulating Paper',
                'category_id' => 10,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'ARP001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Finishing Strips',
                'category_id' => 10,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'FIP001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Hemospoon',
                'category_id' => 10,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'HEM01',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Fuji 1 Big',
                'category_id' => 12,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'FUJ001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Fuji 1 Mini',
                'category_id' => 12,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'FUJ002',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Fuji 1 Repack',
                'category_id' => 12,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'FUJ003',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Fuji II Big',
                'category_id' => 12,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'FUJ004',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Fuji II Mini',
                'category_id' => 12,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'FUJ005',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Fuji II Repack',
                'category_id' => 12,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'FUJ006',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Fuji 9 Big',
                'category_id' => 12,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'FUJ007',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Fuji 9 Mini',
                'category_id' => 12,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'FUJ008',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'IRM Big',
                'category_id' => 12,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'IRM001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'IRM Repack',
                'category_id' => 12,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'IRM002',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Tremex Big',
                'category_id' => 12,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'TRE001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Tremex Small',
                'category_id' => 12,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'TRE002',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Tempak Zoe',
                'category_id' => 12,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'TEZ001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Ionocem',
                'category_id' => 12,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'ION001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'U-Cem Universal Resin Cement',
                'category_id' => 12,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'URC001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Dual-Core Automix Build-up Material',
                'category_id' => 12,
                'brand_id' => 23,
                'suppliers_id' => 1,
                'stock' => 40,
                'stock_warning' => 20,
                'SKU' => 'DCA001',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]

=======
            ],

            [
                'name' => 'Castone',
                'category_id' => 5,
                'brand_id' => 1,
                'stock' => 40,
                'SKU' => 'Cas2345',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'name' => 'Diestone',
                'category_id' => 5,
                'brand_id' => 1,
                'stock' => 50,
                'SKU' => 'Cas234',
                'cprice' => 100.00,
                'sprice' => 180.00,
                'weight' => 5,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'name' => 'Plaster',
                'category_id' => 5,
                'brand_id' => 1,
                'stock' => 20,
                'SKU' => 'Cas236',
                'cprice' => 20.4,
                'sprice' => 40.00,
                'weight' => 10,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'name' => 'Ortho Plaster',
                'category_id' => 5,
                'brand_id' => 1,
                'stock' => 40,
                'SKU' => 'Cas239',
                'cprice' => 200,
                'sprice' => 240.00,
                'weight' => 35,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'name' => 'Disposable needles',
                'category_id' => 6,
                'brand_id' => 2,
                'stock' => 40,
                'SKU' => 'SUT123',
                'cprice' => 70,
                'sprice' => 100.00,
                'weight' => 36,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Surgical silk',
                'category_id' => 6,
                'brand_id' => 5,
                'stock' => 100,
                'SKU' => 'SUT242',
                'cprice' => 60,
                'sprice' => 85.00,
                'weight' => 33,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Nerve Broach',
                'category_id' => 7,
                'brand_id' => 9,
                'stock' => 3,
                'SKU' => 'Rot242',
                'cprice' => 300,
                'sprice' => 350.00,
                'weight' => 32,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Gutta Percha 15-40',
                'category_id' => 7,
                'brand_id' => 7,
                'stock' => 120,
                'SKU' => 'Rot422',
                'cprice' => 100,
                'sprice' => 200.00,
                'weight' => 55,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Gutta Percha 45 - 80',
                'category_id' => 7,
                'brand_id' => 5,
                'stock' => 100,
                'SKU' => 'Rot421',
                'cprice' => 100,
                'sprice' => 200.00,
                'weight' => 33,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Papper Point 15 - 40',
                'category_id' => 7,
                'brand_id' => 5,
                'stock' => 100,
                'SKU' => 'Rot425',
                'cprice' => 100,
                'sprice' => 200.00,
                'weight' => 31,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Papper Point 45 - 80',
                'category_id' => 7,
                'brand_id' => 5,
                'stock' => 100,
                'SKU' => 'Rot415',
                'cprice' => 100,
                'sprice' => 200.00,
                'weight' => 31,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
>>>>>>> ef57359fd894ee32ceb516246ccc1af1ff09f8aa
        ]);
    }
}
