<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;
use App\Models\Product;
class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('product') ->insert([
            [
                'name' => 'Glorned Gloves',
                'category_id' => 1,
                'brand_id' => 5,
                'stock' => 40,
                'SKU' => 'GLO212',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Microsuper Gloves',
                'category_id' => 1,
                'brand_id' => 5,
                'stock' => 40,
                'SKU' => 'GLO213',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'HCD Gloves',
                'category_id' => 1,
                'brand_id' => 5,
                'stock' => 40,
                'SKU' => 'GLO215',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Defender Mask',
                'category_id' => 2,
                'brand_id' => 8,
                'stock' => 40,
                'SKU' => 'Mas213',
                'cprice' => 100,
                'sprice' => 350.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Ordinary Mask',
                'category_id' => 2,
                'brand_id' => 1,
                'stock' => 40,
                'SKU' => 'Mas234',
                'cprice' => 40,
                'sprice' => 65.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'KN 95',
                'category_id' => 2,
                'brand_id' => 1,
                'stock' => 40,
                'SKU' => 'Mas245',
                'cprice' => 40,
                'sprice' => 35.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => '2ply disposable',
                'category_id' => 3,
                'brand_id' => 6,
                'stock' => 40,
                'SKU' => 'Bb222',
                'cprice' => 40,
                'sprice' => 35.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => '3ply disposable',
                'category_id' => 3,
                'brand_id' => 1,
                'stock' => 40,
                'SKU' => 'Bb223',
                'cprice' => 40,
                'sprice' => 35.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Washable bib Adult',
                'category_id' => 3,
                'brand_id' => 5,
                'stock' => 40,
                'SKU' => 'Bb224',
                'cprice' => 40,
                'sprice' => 35.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Washable bib pedo',
                'category_id' => 3,
                'brand_id' => 5,
                'stock' => 40,
                'SKU' => 'Bb225',
                'cprice' => 40,
                'sprice' => 180.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Saliva Injector Wordwork',
                'category_id' => 4,
                'brand_id' => 5,
                'stock' => 40,
                'SKU' => 'SUC111',
                'cprice' => 40,
                'sprice' => 150.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Saliva Injector Micro',
                'category_id' => 4,
                'brand_id' => 5,
                'stock' => 40,
                'SKU' => 'SUC112',
                'cprice' => 40,
                'sprice' => 150.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Saliva Injector Flexi',
                'category_id' => 4,
                'brand_id' => 5,
                'stock' => 40,
                'SKU' => 'SUC113',
                'cprice' => 40,
                'sprice' => 150.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'High Vacuum',
                'category_id' => 4,
                'brand_id' => 5,
                'stock' => 40,
                'SKU' => 'SUC114',
                'cprice' => 40,
                'sprice' => 200.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Surgical Sunction Tip',
                'category_id' => 4,
                'brand_id' => 5,
                'stock' => 40,
                'SKU' => 'SUC115',
                'cprice' => 40,
                'sprice' => 200.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name' => 'Castone',
                'category_id' => 5,
                'brand_id' => 1,
                'stock' => 40,
                'SKU' => 'Cas2345',
                'cprice' => 40,
                'sprice' => 80.00,
                'weight' => 30.4,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'name' => 'Diestone',
                'category_id' => 5,
                'brand_id' => 1,
                'stock' => 50,
                'SKU' => 'Cas234',
                'cprice' => 100.00,
                'sprice' => 180.00,
                'weight' => 5,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'name' => 'Plaster',
                'category_id' => 5,
                'brand_id' => 1,
                'stock' => 20,
                'SKU' => 'Cas236',
                'cprice' => 20.4,
                'sprice' => 40.00,
                'weight' => 10,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'name' => 'Ortho Plaster',
                'category_id' => 5,
                'brand_id' => 1,
                'stock' => 40,
                'SKU' => 'Cas239',
                'cprice' => 200,
                'sprice' => 240.00,
                'weight' => 35,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'name' => 'Disposable needles',
                'category_id' => 6,
                'brand_id' => 2,
                'stock' => 40,
                'SKU' => 'SUT123',
                'cprice' => 70,
                'sprice' => 100.00,
                'weight' => 36,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Surgical silk',
                'category_id' => 6,
                'brand_id' => 5,
                'stock' => 100,
                'SKU' => 'SUT242',
                'cprice' => 60,
                'sprice' => 85.00,
                'weight' => 33,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Nerve Broach',
                'category_id' => 7,
                'brand_id' => 9,
                'stock' => 3,
                'SKU' => 'Rot242',
                'cprice' => 300,
                'sprice' => 350.00,
                'weight' => 32,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Gutta Percha 15-40',
                'category_id' => 7,
                'brand_id' => 7,
                'stock' => 120,
                'SKU' => 'Rot422',
                'cprice' => 100,
                'sprice' => 200.00,
                'weight' => 55,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Gutta Percha 45 - 80',
                'category_id' => 7,
                'brand_id' => 5,
                'stock' => 100,
                'SKU' => 'Rot421',
                'cprice' => 100,
                'sprice' => 200.00,
                'weight' => 33,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Papper Point 15 - 40',
                'category_id' => 7,
                'brand_id' => 5,
                'stock' => 100,
                'SKU' => 'Rot425',
                'cprice' => 100,
                'sprice' => 200.00,
                'weight' => 31,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Papper Point 45 - 80',
                'category_id' => 7,
                'brand_id' => 5,
                'stock' => 100,
                'SKU' => 'Rot415',
                'cprice' => 100,
                'sprice' => 200.00,
                'weight' => 31,
                'status' => 1,
                'description' => "This is a test product",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
