@extends('customer.layout.base')
@section('content')  
@section('title', 'Privacy Policy')
<header>
    
</header>
<section>
    <div class="flex justify-center">
        <div class="intro-y box py-10 sm:py-20 mt-5">
            <div class="px-2 mt-5">
                <div class="font-medium text-center text-lg">Privacy Policy</div>
                <div class="text-slate-500 text-center mt-2">Go Dental Privacy Policy</div>
            </div>
            <div class="px-5 sm:px-20 mt-10 pt-10 border-t border-slate-200/60 dark:border-darkmode-400">
            
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse facilisis ornare feugiat. Sed nec justo et justo gravida ornare. Nullam tincidunt accumsan ultrices. Ut vehicula enim non justo sollicitudin tempor. Duis urna tortor, auctor vel mi sed, luctus ornare quam. Pellentesque dictum semper metus, eu ornare leo. Pellentesque facilisis vehicula enim, sit amet dapibus purus scelerisque ac. Morbi pretium ligula et suscipit sodales. Duis varius pretium urna. Integer non ante a magna feugiat auctor.

                Sed vestibulum condimentum diam et blandit. Etiam ac diam ut erat cursus ullamcorper. Nunc porttitor, odio a eleifend interdum, nibh urna feugiat tortor, ac ultrices urna ante at quam. Mauris sed pulvinar tortor. In id aliquam nibh. Nunc a lorem aliquet, aliquet purus vel, ultricies ligula. Etiam lobortis dolor at porta laoreet.
                
                Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
                
                Curabitur euismod leo condimentum sem egestas, vitae commodo purus fermentum. Pellentesque fringilla dui ut viverra venenatis. Mauris lobortis sollicitudin interdum. Duis sed lorem varius, eleifend odio at, condimentum nulla. Nullam tempus quam eleifend, scelerisque tellus ut, venenatis lorem. Aliquam sagittis ornare nibh, at pulvinar justo tristique vitae. Morbi et neque dignissim, pretium turpis eget, commodo ante. Praesent iaculis ultrices augue in ornare. Integer tristique ligula ante, vitae auctor metus finibus sit amet. Duis ornare accumsan magna, et egestas mauris faucibus vitae. Nulla a mattis sem. Aliquam enim ipsum, fermentum a libero a, rutrum efficitur felis. Curabitur at enim accumsan, vulputate risus in, tristique orci. Nam condimentum sapien viverra risus molestie rutrum. Praesent eget sapien molestie nunc porttitor ullamcorper. Nullam posuere ligula diam, et molestie urna fringilla sed.
                
                Duis varius lorem in nunc eleifend bibendum non ac ligula. In fringilla placerat placerat. Maecenas volutpat vitae ex suscipit eleifend. Donec finibus eget arcu vel auctor. Integer vel ipsum non ipsum gravida fermentum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin pretium, lacus bibendum malesuada faucibus, velit dui tempus purus, ornare lobortis nulla libero id lacus. Aliquam gravida feugiat purus, et euismod sem fermentum ornare. Aliquam cursus risus ut ornare pulvinar. Sed condimentum lorem condimentum neque aliquam dictum sed nec metus. Pellentesque sit amet ultrices neque. Praesent viverra velit enim, sed ultrices risus pellentesque a. Cras urna dolor, rhoncus sed imperdiet non, lobortis non velit.
                <div class="font-medium text-base mt-1 mb-1">1. Introduction</div>
                Duis varius lorem in nunc eleifend bibendum non ac ligula. In fringilla placerat placerat. Maecenas volutpat vitae ex suscipit eleifend. Donec finibus eget arcu vel auctor. Integer vel ipsum non ipsum gravida fermentum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin pretium, lacus bibendum malesuada faucibus, velit dui tempus purus, ornare lobortis nulla libero id lacus. Aliquam gravida feugiat purus, et euismod sem fermentum ornare. Aliquam cursus risus ut ornare pulvinar. Sed condimentum lorem condimentum neque aliquam dictum sed nec metus. Pellentesque sit amet ultrices neque. Praesent viverra velit enim, sed ultrices risus pellentesque a. Cras urna dolor, rhoncus sed imperdiet non, lobortis non velit.
                <div class="font-medium text-base mt-1 mb-1">2. When will Go Dental Collect Personal Data</div>
                Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
                
                Curabitur euismod leo condimentum sem egestas, vitae commodo purus fermentum. Pellentesque fringilla dui ut viverra venenatis. Mauris lobortis sollicitudin interdum. Duis sed lorem varius, eleifend odio at, condimentum nulla. Nullam tempus quam eleifend, scelerisque tellus ut, venenatis lorem. Aliquam sagittis ornare nibh, at pulvinar justo tristique vitae. Morbi et neque dignissim, pretium turpis eget, commodo ante. Praesent iaculis ultrices augue in ornare. Integer tristique ligula ante, vitae auctor metus finibus sit amet. Duis ornare accumsan magna, et egestas mauris faucibus vitae. Nulla a mattis sem. Aliquam enim ipsum, fermentum a libero a, rutrum efficitur felis. Curabitur at enim accumsan, vulputate risus in, tristique orci. Nam condimentum sapien viverra risus molestie rutrum. Praesent eget sapien molestie nunc porttitor 
                <div class="font-medium text-base mt-1 mb-1">3. What Personal Data will Go Dental Collect</div>
                Sed vestibulum condimentum diam et blandit. Etiam ac diam ut erat cursus ullamcorper. Nunc porttitor, odio a eleifend interdum, nibh urna feugiat tortor, ac ultrices urna ante at quam. Mauris sed pulvinar tortor. In id aliquam nibh. Nunc a lorem aliquet, aliquet purus vel, ultricies ligula. Etiam lobortis dolor at porta laoreet.
                <div class="font-medium text-base mt-1 mb-1">4. Customer with Go Dental Accounts</div>
                Sed vestibulum condimentum diam et blandit. Etiam ac diam ut erat cursus ullamcorper. Nunc porttitor, odio a eleifend interdum, nibh urna feugiat tortor, ac ultrices urna ante at quam. Mauris sed pulvinar tortor. In id aliquam nibh. Nunc a lorem aliquet, aliquet purus vel, ultricies ligula. Etiam lobortis dolor at porta laoreet.
                Sed vestibulum condimentum diam et blandit. Etiam ac diam ut erat cursus ullamcorper. Nunc porttitor, odio a eleifend interdum, nibh urna feugiat tortor, ac ultrices urna ante at quam. Mauris sed pulvinar tortor. In id aliquam nibh. Nunc a lorem aliquet, aliquet purus vel, ultricies ligula. Etiam lobortis dolor at porta laoreet.
                
                Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
                
                Curabitur euismod leo condimentum sem egestas, vitae commodo purus fermentum. Pellentesque fringilla dui ut viverra venenatis. Mauris lobortis sollicitudin interdum. Duis sed lorem varius, eleifend odio at, condimentum nulla. Nullam tempus quam eleifend, scelerisque tellus ut, venenatis lorem. Aliquam sagittis ornare nibh, at pulvinar justo tristique vitae. Morbi et neque dignissim, pretium turpis eget, commodo ante. Praesent iaculis ultrices augue in ornare. Integer tristique ligula ante, vitae auctor metus finibus sit amet. Duis ornare accumsan magna, et egestas mauris faucibus vitae. Nulla a mattis sem. Aliquam enim ipsum, fermentum a libero a, rutrum efficitur felis. Curabitur at enim accumsan, vulputate risus in, tristique orci. Nam condimentum sapien viverra risus molestie rutrum. Praesent eget sapien molestie nunc porttitor ullamcorper. Nullam posuere ligula diam, et molestie urna fringilla sed.
                <div class="font-medium text-base mt-1 mb-1">5. Collection of Other Data</div>
                Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
                <div class="font-medium text-base mt-1 mb-1">6. Cookies</div>
                Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
                <div class="font-medium text-base mt-1 mb-1">7. How do we use the information you provide us?</div>
                Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
                <div class="font-medium text-base mt-1 mb-1">8. How does Go Dental protect and retain customer information</div>
                Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
                <div class="font-medium text-base mt-1 mb-1">9. Does Go Dental Disclose the information it collects form its visitors to outside parties?</div>
                Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
                <div class="font-medium text-base mt-1 mb-1">10. Information Collected by Third Parties</div>
                Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
                <div class="font-medium text-base mt-1 mb-1">11. Disclaimer regarding security and third party sites</div>
                Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
                <div class="font-medium text-base mt-1 mb-1">12. Will Go Dental Transfer your information overseas?</div>
                Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
                <div class="font-medium text-base mt-1 mb-1">13. How can you withdraw consent, Request Access to or collect information you have provided us?</div>
                Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
            </div>
        </div>
    </div>
</section>

@endsection 
@push('scripts')
<script>
</script>
@endpush