@extends('customer.layout.base')
@section('content')  
@section('title', 'Terms')

<!-- BEGIN: Wizard Layout -->
<div class="flex justify-center">
<div class="intro-y box py-10 sm:py-20 mt-5 	">
    <div class="px-2 mt-5">
        <div class="font-medium text-center text-lg">Terms of Use</div>
        <div class="text-slate-500 text-center mt-2">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </div>
    </div>
    <div class="px-5 sm:px-20 mt-10 pt-10 border-t border-slate-200/60 dark:border-darkmode-400">
     
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse facilisis ornare feugiat. Sed nec justo et justo gravida ornare. Nullam tincidunt accumsan ultrices. Ut vehicula enim non justo sollicitudin tempor. Duis urna tortor, auctor vel mi sed, luctus ornare quam. Pellentesque dictum semper metus, eu ornare leo. Pellentesque facilisis vehicula enim, sit amet dapibus purus scelerisque ac. Morbi pretium ligula et suscipit sodales. Duis varius pretium urna. Integer non ante a magna feugiat auctor.

        Sed vestibulum condimentum diam et blandit. Etiam ac diam ut erat cursus ullamcorper. Nunc porttitor, odio a eleifend interdum, nibh urna feugiat tortor, ac ultrices urna ante at quam. Mauris sed pulvinar tortor. In id aliquam nibh. Nunc a lorem aliquet, aliquet purus vel, ultricies ligula. Etiam lobortis dolor at porta laoreet.
        
        Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
        
        Curabitur euismod leo condimentum sem egestas, vitae commodo purus fermentum. Pellentesque fringilla dui ut viverra venenatis. Mauris lobortis sollicitudin interdum. Duis sed lorem varius, eleifend odio at, condimentum nulla. Nullam tempus quam eleifend, scelerisque tellus ut, venenatis lorem. Aliquam sagittis ornare nibh, at pulvinar justo tristique vitae. Morbi et neque dignissim, pretium turpis eget, commodo ante. Praesent iaculis ultrices augue in ornare. Integer tristique ligula ante, vitae auctor metus finibus sit amet. Duis ornare accumsan magna, et egestas mauris faucibus vitae. Nulla a mattis sem. Aliquam enim ipsum, fermentum a libero a, rutrum efficitur felis. Curabitur at enim accumsan, vulputate risus in, tristique orci. Nam condimentum sapien viverra risus molestie rutrum. Praesent eget sapien molestie nunc porttitor ullamcorper. Nullam posuere ligula diam, et molestie urna fringilla sed.
        
        Duis varius lorem in nunc eleifend bibendum non ac ligula. In fringilla placerat placerat. Maecenas volutpat vitae ex suscipit eleifend. Donec finibus eget arcu vel auctor. Integer vel ipsum non ipsum gravida fermentum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin pretium, lacus bibendum malesuada faucibus, velit dui tempus purus, ornare lobortis nulla libero id lacus. Aliquam gravida feugiat purus, et euismod sem fermentum ornare. Aliquam cursus risus ut ornare pulvinar. Sed condimentum lorem condimentum neque aliquam dictum sed nec metus. Pellentesque sit amet ultrices neque. Praesent viverra velit enim, sed ultrices risus pellentesque a. Cras urna dolor, rhoncus sed imperdiet non, lobortis non velit.
        <div class="font-medium text-base mt-1 mb-1">1. Definition & Interpretation</div>
        Duis varius lorem in nunc eleifend bibendum non ac ligula. In fringilla placerat placerat. Maecenas volutpat vitae ex suscipit eleifend. Donec finibus eget arcu vel auctor. Integer vel ipsum non ipsum gravida fermentum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin pretium, lacus bibendum malesuada faucibus, velit dui tempus purus, ornare lobortis nulla libero id lacus. Aliquam gravida feugiat purus, et euismod sem fermentum ornare. Aliquam cursus risus ut ornare pulvinar. Sed condimentum lorem condimentum neque aliquam dictum sed nec metus. Pellentesque sit amet ultrices neque. Praesent viverra velit enim, sed ultrices risus pellentesque a. Cras urna dolor, rhoncus sed imperdiet non, lobortis non velit.
        <div class="font-medium text-base mt-1 mb-1">2. General use of Services and/or access of Platform</div>
        Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
        
        Curabitur euismod leo condimentum sem egestas, vitae commodo purus fermentum. Pellentesque fringilla dui ut viverra venenatis. Mauris lobortis sollicitudin interdum. Duis sed lorem varius, eleifend odio at, condimentum nulla. Nullam tempus quam eleifend, scelerisque tellus ut, venenatis lorem. Aliquam sagittis ornare nibh, at pulvinar justo tristique vitae. Morbi et neque dignissim, pretium turpis eget, commodo ante. Praesent iaculis ultrices augue in ornare. Integer tristique ligula ante, vitae auctor metus finibus sit amet. Duis ornare accumsan magna, et egestas mauris faucibus vitae. Nulla a mattis sem. Aliquam enim ipsum, fermentum a libero a, rutrum efficitur felis. Curabitur at enim accumsan, vulputate risus in, tristique orci. Nam condimentum sapien viverra risus molestie rutrum. Praesent eget sapien molestie nunc porttitor 
        <div class="font-medium text-base mt-1 mb-1">3. Use of Services</div>
        Sed vestibulum condimentum diam et blandit. Etiam ac diam ut erat cursus ullamcorper. Nunc porttitor, odio a eleifend interdum, nibh urna feugiat tortor, ac ultrices urna ante at quam. Mauris sed pulvinar tortor. In id aliquam nibh. Nunc a lorem aliquet, aliquet purus vel, ultricies ligula. Etiam lobortis dolor at porta laoreet.
        <div class="font-medium text-base mt-1 mb-1">4. Customer with Go Dental Accounts</div>
        Sed vestibulum condimentum diam et blandit. Etiam ac diam ut erat cursus ullamcorper. Nunc porttitor, odio a eleifend interdum, nibh urna feugiat tortor, ac ultrices urna ante at quam. Mauris sed pulvinar tortor. In id aliquam nibh. Nunc a lorem aliquet, aliquet purus vel, ultricies ligula. Etiam lobortis dolor at porta laoreet.
        Sed vestibulum condimentum diam et blandit. Etiam ac diam ut erat cursus ullamcorper. Nunc porttitor, odio a eleifend interdum, nibh urna feugiat tortor, ac ultrices urna ante at quam. Mauris sed pulvinar tortor. In id aliquam nibh. Nunc a lorem aliquet, aliquet purus vel, ultricies ligula. Etiam lobortis dolor at porta laoreet.
        
        Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
        
        Curabitur euismod leo condimentum sem egestas, vitae commodo purus fermentum. Pellentesque fringilla dui ut viverra venenatis. Mauris lobortis sollicitudin interdum. Duis sed lorem varius, eleifend odio at, condimentum nulla. Nullam tempus quam eleifend, scelerisque tellus ut, venenatis lorem. Aliquam sagittis ornare nibh, at pulvinar justo tristique vitae. Morbi et neque dignissim, pretium turpis eget, commodo ante. Praesent iaculis ultrices augue in ornare. Integer tristique ligula ante, vitae auctor metus finibus sit amet. Duis ornare accumsan magna, et egestas mauris faucibus vitae. Nulla a mattis sem. Aliquam enim ipsum, fermentum a libero a, rutrum efficitur felis. Curabitur at enim accumsan, vulputate risus in, tristique orci. Nam condimentum sapien viverra risus molestie rutrum. Praesent eget sapien molestie nunc porttitor ullamcorper. Nullam posuere ligula diam, et molestie urna fringilla sed.
        <div class="font-medium text-base mt-1 mb-1">5. Intellectual property</div>
        Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
        <div class="font-medium text-base mt-1 mb-1">6. Our Limitation of responsibility and liability</div>
        Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
        <div class="font-medium text-base mt-1 mb-1">7. Hyperlinks and alerts</div>
        Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
        <div class="font-medium text-base mt-1 mb-1">8. Your submission and information</div>
        Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
        <div class="font-medium text-base mt-1 mb-1">9. Termination</div>
        Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
        <div class="font-medium text-base mt-1 mb-1">10. Notices</div>
        Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
        <div class="font-medium text-base mt-1 mb-1">11. General</div>
        Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
        <div class="font-medium text-base mt-1 mb-1">12. Voucher Terms & Condition</div>
        Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
        <div class="font-medium text-base mt-1 mb-1">13. Your submission and information</div>
        Fusce euismod, erat in facilisis faucibus, metus neque condimentum felis, euismod cursus tortor lacus in nisl. Sed vel urna at arcu tempus viverra ut et sem. Integer mollis sem ac augue viverra, et rutrum elit porta. Etiam posuere luctus hendrerit. Ut porta eleifend nulla, at eleifend erat dictum id. Cras luctus, risus sit amet dapibus ullamcorper, mi metus sollicitudin elit, ultrices condimentum est lorem quis velit. Curabitur a magna lectus. Morbi at nisi sagittis, feugiat purus venenatis, efficitur urna. Phasellus et facilisis lacus.
        </div>
    </div>
</div>

@endsection 
@push('scripts')
<script>
</script>
@endpush